services:
  ergo:
    image: ghcr.io/ergochat/ergo:stable
    init: true
    ports:
      - "6667:6667/tcp"
      - "6697:6697/tcp"
    volumes:
      - ergo:/ircd
  mongodb:
    image: mongo:5
    ports:
      - "27017:27017/tcp"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379/tcp"
  wheaties:
    build: .
    environment:
      MONGODB_URL: mongodb://mongodb:27017/wheaties
      REDIS_URL: redis://redis
    env_file: docker.env
    depends_on:
      - ergo
      - mongodb
      - redis

volumes:
  ergo:
