version: '3'
services:
  mongodb:
    image: mongo:3.6
  redis:
    image: redis:alpine
  wheaties:
    build: .
    environment:
      MONGODB_URL: mongodb://mongodb:27017/wheaties
    env_file: docker.env
    depends_on:
      - mongodb
      - redis
