services:
  mongodb:
    image: mongo:5
  redis:
    image: redis:alpine
  wheaties:
    build: .
    environment:
      MONGODB_URL: mongodb://mongodb:27017/wheaties
      REDIS_URL: redis://redis
    env_file: docker.env
    depends_on:
      - mongodb
      - redis
